In [1]:
import numpy as np
arr = np.array([1,3,4,5,6])
arr


array([1, 3, 4, 5, 6])

In [3]:
arr.shape

(5,)

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr = np.array([1,'st','er',3])
arr.dtype

dtype('<U11')

In [7]:
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])#creating the array
arr.shape

(3, 3)

In [8]:
arr

array([[1, 2, 3],
       [2, 4, 6],
       [8, 8, 8]])

In [9]:
arr = np.zeros((2,4))

In [10]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
arr = np.ones((2,4))

In [12]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
arr = np.identity(3)

In [14]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
arr = np.random.randn(3,4)

In [16]:
arr

array([[ 1.46163038, -0.68223424,  0.76423411, -0.14036992],
       [ 0.3665935 ,  1.08863602,  0.30887436, -0.687826  ],
       [-0.26957197, -1.95031672,  0.47583999, -0.66469059]])

In [17]:
from io import BytesIO
b = BytesIO(b"2,23,33\n32,42,63.4\n35,77,12")
arr = np.genfromtxt(b, delimiter=",")


In [18]:
arr

array([[ 2. , 23. , 33. ],
       [32. , 42. , 63.4],
       [35. , 77. , 12. ]])

In [19]:
arr[1]

array([32. , 42. , 63.4])

In [20]:
arr = np.arange(12).reshape(2,2,3)

In [21]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [22]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
arr = np.arange(10)

In [24]:
arr[5:]

array([5, 6, 7, 8, 9])

In [25]:
arr[4:9]

array([4, 5, 6, 7, 8])

In [26]:
arr = np.arange(10)

In [27]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [28]:
arr[4:9]

array([4, 5, 6, 7, 8])

In [29]:
arr[:-4]

array([0, 1, 2, 3, 4, 5])

## Negative implies we need to subtract

In [30]:
arr = np.arange(12).reshape(2,2,3)

In [31]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [32]:
arr[1:3]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [33]:
arr = np.arange(27).reshape(3,3,3)

In [34]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
arr[:,:,2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [36]:
arr[...,2]


array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [37]:
arr = np.arange(9).reshape(3,3)

In [38]:
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:

arr[[0,1,2],[1,0,0]]

array([1, 3, 6])

In [40]:
cities = np.array(["delhi","banglaore","mumbai","chennai","bhopal"])
city_data = np.random.randn(5,3)
city_data

array([[-1.82136032,  0.16021191, -1.77678794],
       [-0.92839813,  0.25363398,  0.14318001],
       [-0.07842458, -0.42074637,  0.01668284],
       [ 0.28716089, -1.2078002 , -0.06067175],
       [-1.51827512, -2.16548823, -1.34754482]])

In [41]:
city_data[cities =="delhi"]

array([[-1.82136032,  0.16021191, -1.77678794]])

In [42]:
city_data[city_data >0]

array([0.16021191, 0.25363398, 0.14318001, 0.01668284, 0.28716089])

In [43]:
city_data[city_data >0] = 0
city_data

array([[-1.82136032,  0.        , -1.77678794],
       [-0.92839813,  0.        ,  0.        ],
       [-0.07842458, -0.42074637,  0.        ],
       [ 0.        , -1.2078002 , -0.06067175],
       [-1.51827512, -2.16548823, -1.34754482]])

In [44]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:

arr + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
arr * 5

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70]])

In [47]:
arr / 2

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ]])

In [48]:
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(5).reshape(5,1)
arr2 + arr1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [49]:

arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [50]:
arr2

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [51]:
arr1 = np.random.randn(5,3)

In [52]:
arr1

array([[ 0.7059042 ,  0.77661141,  1.18897651],
       [-0.83389039, -0.95008426,  0.59975563],
       [-1.15124655,  0.55215645, -0.58459989],
       [-1.28906252, -0.59357085, -0.82620172],
       [-1.84868697,  0.03325715, -1.84549704]])

In [53]:
np.modf(arr1)

(array([[ 0.7059042 ,  0.77661141,  0.18897651],
        [-0.83389039, -0.95008426,  0.59975563],
        [-0.15124655,  0.55215645, -0.58459989],
        [-0.28906252, -0.59357085, -0.82620172],
        [-0.84868697,  0.03325715, -0.84549704]]), array([[ 0.,  0.,  1.],
        [-0., -0.,  0.],
        [-1.,  0., -0.],
        [-1., -0., -0.],
        [-1.,  0., -1.]]))

In [54]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[1,2,3]])
A.dot(B)

array([[ 24,  24,  24],
       [ 72,  69,  66],
       [120, 114, 108]])

In [55]:
A = np.arange(15).reshape(3,5)
A.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [56]:
a = np.array([[7,5,-3], [3,-5,2],[5,3,-7]])
b = np.array([16,-8,0])
x = np.linalg.solve(a, b)
x

array([1., 3., 2.])

In [57]:

np.allclose(np.dot(a, x),b)

True

In [58]:

import pandas as pd
d =  [{'city':'Delhi',"data":1000},
      {'city':'Banglaore',"data":2000},
      {'city':'Mumbai',"data":1000}]
pd.DataFrame(d)

city  data
0      Delhi  1000
1  Banglaore  2000
2     Mumbai  1000

In [59]:
df = pd.DataFrame(d)

In [61]:

city_data = pd.read_csv(filepath_or_buffer='simplemaps-worldcities-basic.csv')

In [62]:
city_data.head(n=10)

city      city_ascii        lat        lng       pop  \
0   Qal eh-ye Now       Qal eh-ye  34.983000  63.133300    2997.0   
1     Chaghcharan     Chaghcharan  34.516701  65.250001   15000.0   
2     Lashkar Gah     Lashkar Gah  31.582998  64.360000  201546.0   
3          Zaranj          Zaranj  31.112001  61.886998   49851.0   
4      Tarin Kowt      Tarin Kowt  32.633298  65.866699   10000.0   
5    Zareh Sharan    Zareh Sharan  32.850000  68.416705   13737.0   
6        Asadabad        Asadabad  34.866000  71.150005   48400.0   
7         Taloqan         Taloqan  36.729999  69.540004   64256.0   
8  Mahmud-E Eraqi  Mahmud-E Eraqi  35.016696  69.333301    7407.0   
9      Mehtar Lam      Mehtar Lam  34.650000  70.166701   17345.0   

       country iso2 iso3 province  
0  Afghanistan   AF  AFG  Badghis  
1  Afghanistan   AF  AFG     Ghor  
2  Afghanistan   AF  AFG  Hilmand  
3  Afghanistan   AF  AFG   Nimroz  
4  Afghanistan   AF  AFG  Uruzgan  
5  Afghanistan   AF  AFG  Paktika  
6  Afghanistan   AF  AFG    Kunar  
7  Afghanistan   AF  AFG   Takhar  
8  Afghanistan   AF  AFG   Kapisa  
9  Afghanistan   AF  AFG  Laghman

In [63]:
city_data.tail()

city   city_ascii        lat        lng        pop   country  \
7317       Mutare       Mutare -18.970019  32.650038   216785.0  Zimbabwe   
7318       Kadoma       Kadoma -18.330006  29.909947    56400.0  Zimbabwe   
7319  Chitungwiza  Chitungwiza -18.000001  31.100003   331071.0  Zimbabwe   
7320       Harare       Harare -17.817790  31.044709  1557406.5  Zimbabwe   
7321     Bulawayo     Bulawayo -20.169998  28.580002   697096.0  Zimbabwe   

     iso2 iso3          province  
7317   ZW  ZWE        Manicaland  
7318   ZW  ZWE  Mashonaland West  
7319   ZW  ZWE            Harare  
7320   ZW  ZWE            Harare  
7321   ZW  ZWE          Bulawayo

In [64]:
series_es = city_data.lat

In [65]:

series_es[1:10:2]

1    34.516701
3    31.112001
5    32.850000
7    36.729999
9    34.650000
Name: lat, dtype: float64

In [66]:
type(series_es)

pandas.core.series.Series

In [67]:
series_es[:7]

0    34.983000
1    34.516701
2    31.582998
3    31.112001
4    32.633298
5    32.850000
6    34.866000
Name: lat, dtype: float64

In [68]:

city_data[:7]

city    city_ascii        lat        lng       pop      country  \
0  Qal eh-ye Now     Qal eh-ye  34.983000  63.133300    2997.0  Afghanistan   
1    Chaghcharan   Chaghcharan  34.516701  65.250001   15000.0  Afghanistan   
2    Lashkar Gah   Lashkar Gah  31.582998  64.360000  201546.0  Afghanistan   
3         Zaranj        Zaranj  31.112001  61.886998   49851.0  Afghanistan   
4     Tarin Kowt    Tarin Kowt  32.633298  65.866699   10000.0  Afghanistan   
5   Zareh Sharan  Zareh Sharan  32.850000  68.416705   13737.0  Afghanistan   
6       Asadabad      Asadabad  34.866000  71.150005   48400.0  Afghanistan   

  iso2 iso3 province  
0   AF  AFG  Badghis  
1   AF  AFG     Ghor  
2   AF  AFG  Hilmand  
3   AF  AFG   Nimroz  
4   AF  AFG  Uruzgan  
5   AF  AFG  Paktika  
6   AF  AFG    Kunar

In [69]:
city_data.iloc[:5,:4]

city   city_ascii        lat        lng
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300
1    Chaghcharan  Chaghcharan  34.516701  65.250001
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000
3         Zaranj       Zaranj  31.112001  61.886998
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699

In [70]:
city_data[city_data['pop'] > 10000000][city_data.columns[pd.Series(city_data.columns).str.startswith('l')]]

lat         lng
360  -34.602502  -58.397531
1171 -23.558680  -46.625020
2068  31.216452  121.436505
3098  28.669993   77.230004
3110  19.016990   72.856989
3492  35.685017  139.751407
4074  19.442442  -99.130988
4513  24.869992   66.990009
5394  55.752164   37.615523
6124  41.104996   29.010002
7071  40.749979  -73.980017

In [71]:
df = pd.DataFrame(np.random.randn(8, 3),
columns=['A', 'B', 'C'])

In [72]:
nparray = df.values
type(nparray)

numpy.ndarray

In [73]:
from numpy import nan
df.iloc[4,2] = nan

In [74]:
df

A         B         C
0  1.660592 -0.165808  1.139906
1 -1.140574 -1.574223 -1.694008
2  0.511640 -1.227766 -1.224009
3  0.143919  1.962625 -0.531481
4  0.271795  0.456827       NaN
5  0.832764  0.374236 -0.862795
6 -1.553549  0.434220  0.537353
7  0.533325  1.512343 -0.608544

In [75]:

df.fillna(0)

A         B         C
0  1.660592 -0.165808  1.139906
1 -1.140574 -1.574223 -1.694008
2  0.511640 -1.227766 -1.224009
3  0.143919  1.962625 -0.531481
4  0.271795  0.456827  0.000000
5  0.832764  0.374236 -0.862795
6 -1.553549  0.434220  0.537353
7  0.533325  1.512343 -0.608544

In [76]:

columns_numeric = ['lat','lng','pop']
city_data[columns_numeric].mean()

lat        20.662876
lng        10.711914
pop    265463.071633
dtype: float64

In [77]:

city_data[columns_numeric].sum()

lat    1.512936e+05
lng    7.843263e+04
pop    1.943721e+09
dtype: float64

In [78]:
city_data[columns_numeric].count()

lat    7322
lng    7322
pop    7322
dtype: int64

In [79]:
city_data[columns_numeric].median()

lat       26.792730
lng       18.617509
pop    61322.750000
dtype: float64

In [80]:
city_data[columns_numeric].sum(axis = 1).head()

0      3095.116300
1     15099.766702
2    201641.942998
3     49943.998999
4     10098.499997
dtype: float64

In [81]:
city_data[columns_numeric].describe()

lat          lng           pop
count  7322.000000  7322.000000  7.322000e+03
mean     20.662876    10.711914  2.654631e+05
std      29.134818    79.044615  8.287622e+05
min     -89.982894  -179.589979 -9.900000e+01
25%      -0.324710   -64.788472  1.734425e+04
50%      26.792730    18.617509  6.132275e+04
75%      43.575448    73.103628  2.001726e+05
max      82.483323   179.383304  2.200630e+07

In [82]:
city_data1 = city_data.sample(3)
city_data2 = city_data.sample(3)
city_data_combine = pd.concat([city_data1,city_data2])
city_data_combine

city city_ascii        lat         lng        pop  \
661   Charleroi  Charleroi  50.420397    4.450002   272749.5   
6547  Bremerton  Bremerton  47.573596 -122.642018    82039.5   
1090  Araguaina  Araguaina  -7.190015  -48.210014    50444.0   
2171      Aketi      Aketi   2.740464   23.779985    46881.0   
1753     Quiemo     Quiemo  38.133756   85.533321    32494.0   
3059     Rajkot     Rajkot  22.310019   70.800009  1179941.0   

                       country iso2 iso3                province  
661                    Belgium   BE  BEL               Charleroi  
6547  United States of America   US  USA              Washington  
1090                    Brazil   BR  BRA               Tocantins  
2171          Congo (Kinshasa)   CD  COD               Orientale  
1753                     China   CN  CHN          Xinjiang Uygur  
3059                     India   IN  IND  Dadra and Nagar Haveli

In [83]:
df1 = pd.DataFrame({'col1': ['col10', 'col11', 'col12', 'col13'],
                    'col2': ['col20', 'col21', 'col22', 'col23'],
                    'col3': ['col30', 'col31', 'col32', 'col33'],
                    'col4': ['col40', 'col41', 'col42', 'col43']},
                   index=[0, 1, 2, 3])
df1

col1   col2   col3   col4
0  col10  col20  col30  col40
1  col11  col21  col31  col41
2  col12  col22  col32  col42
3  col13  col23  col33  col43

In [84]:
df4 = pd.DataFrame({'col2': ['col22', 'col23', 'col26', 'col27'],
                    'Col4': ['Col42', 'Col43', 'Col46', 'Col47'],
                    'col6': ['col62', 'col63', 'col66', 'col67']},
                   index=[2, 3, 6, 7])

pd.concat([df1,df4], axis=1)

col1   col2   col3   col4   col2   Col4   col6
0  col10  col20  col30  col40    NaN    NaN    NaN
1  col11  col21  col31  col41    NaN    NaN    NaN
2  col12  col22  col32  col42  col22  Col42  col62
3  col13  col23  col33  col43  col23  Col43  col63
6    NaN    NaN    NaN    NaN  col26  Col46  col66
7    NaN    NaN    NaN    NaN  col27  Col47  col67

In [85]:
country_data = city_data[['iso3','country']].drop_duplicates()
country_data.shape

(223, 2)

In [86]:
country_data.head()

iso3         country
0    AFG     Afghanistan
33   ALD           Aland
34   ALB         Albania
60   DZA         Algeria
111  ASM  American Samoa

In [87]:
country_data.tail()

iso3         country
7187  VNM         Vietnam
7247  SAH  Western Sahara
7248  YEM           Yemen
7268  ZMB          Zambia
7302  ZWE        Zimbabwe

In [88]:
del(city_data['country'])
city_data.merge(country_data, 'inner').head()

city   city_ascii        lat        lng       pop iso2 iso3  \
0  Qal eh-ye Now    Qal eh-ye  34.983000  63.133300    2997.0   AF  AFG   
1    Chaghcharan  Chaghcharan  34.516701  65.250001   15000.0   AF  AFG   
2    Lashkar Gah  Lashkar Gah  31.582998  64.360000  201546.0   AF  AFG   
3         Zaranj       Zaranj  31.112001  61.886998   49851.0   AF  AFG   
4     Tarin Kowt   Tarin Kowt  32.633298  65.866699   10000.0   AF  AFG   

  province      country  
0  Badghis  Afghanistan  
1     Ghor  Afghanistan  
2  Hilmand  Afghanistan  
3   Nimroz  Afghanistan  
4  Uruzgan  Afghanistan

In [89]:
from sklearn import datasets
diabetes = datasets.load_diabetes()
X = diabetes.data[:10]
y = diabetes.target

In [90]:

X[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02269202, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187235,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03199144, -0.04664087]])

In [91]:

y[:10]

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310.])

In [92]:
feature_names=['age', 'sex', 'bmi', 'bp',
               's1', 's2', 's3', 's4', 's5', 's6']

In [93]:
feature_names=['age', 'sex', 'bmi', 'bp',
               's1', 's2', 's3', 's4', 's5', 's6']

In [94]:
from sklearn import datasets
from sklearn.linear_model import Lasso

from sklearn import linear_model, datasets
from sklearn.model_selection import GridSearchCV

diabetes = datasets.load_diabetes()
X_train = diabetes.data[:310]
y_train = diabetes.target[:310]

X_test = diabetes.data[310:]
y_test = diabetes.target[310:]

lasso = Lasso(random_state=0)
alphas = np.logspace(-4, -0.5, 30)

scores = list()
scores_std = list()

estimator = GridSearchCV(lasso,
                         param_grid = dict(alpha=alphas))

estimator.fit(X_train, y_train)

C:\Users\PinakParitosh\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\PinakParitosh\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=0,
   selection='cyclic', tol=0.0001, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'alpha': array([1.00000e-04, 1.32035e-04, 1.74333e-04, 2.30181e-04, 3.03920e-04,
       4.01281e-04, 5.29832e-04, 6.99564e-04, 9.23671e-04, 1.21957e-03,
       1.61026e-03, 2.12611e-03, 2.80722e-03, 3.70651e-03, 4.89390e-03,
       6.46167e-03, 8.53168e-03, 1.12648e-02, 1.48735e-02, 1.96383e-02,
       2.59294e-02, 3.42360e-02, 4.52035e-02, 5.96846e-02, 7.88046e-02,
       1.04050e-01, 1.37382e-01, 1.81393e-01, 2.39503e-01, 3.16228e-01])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [95]:
estimator.best_estimator_

Lasso(alpha=0.02592943797404667, copy_X=True, fit_intercept=True,
   max_iter=1000, normalize=False, positive=False, precompute=False,
   random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [96]:
estimator.predict(X_test)

array([203.42104984, 177.6595529 , 122.62188598, 212.81136958,
       173.61633075, 114.76145025, 202.36033584, 171.70767813,
       164.28694562, 191.29091477, 191.41279009, 288.2772433 ,
       296.47009002, 234.53378413, 210.61427168, 228.62812055,
       156.74489991, 225.08834492, 191.75874632, 102.81600989,
       172.373221  , 111.20843429, 290.22242876, 178.64605207,
        78.13722832,  86.35832297, 256.41378529, 165.99622543,
       121.29260976, 153.48718848, 163.09835143, 180.0932902 ,
       161.4330553 , 155.80211635, 143.70181085, 126.13753819,
       181.06471818, 105.03679977, 131.0479936 ,  90.50606427,
       252.66486639,  84.84786067,  59.41005358, 184.51368208,
       201.46598714, 129.96333913,  90.65641478, 200.10932516,
        55.2884802 , 171.60459062, 195.40750666, 122.14139787,
       231.72783897, 159.49750022, 160.32104862, 165.53701866,
       260.73217736, 259.77213787, 204.69526082, 185.66480969,
        61.09821961, 209.9214333 , 108.50410841, 141.18